name: Test API Integrations

on:
  workflow_dispatch:
  push:
    branches: [main]   # O tu rama principal

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install slack_sdk gspread google-auth google-cloud-firestore requests google-generativeai

      - name: Run integration tests
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_TEST_CHANNEL: ${{ secrets.SLACK_TEST_CHANNEL }}
          SERPAPI_KEY: ${{ secrets.SERPAPI_KEY }}
          SERVICE_ACCOUNT: ${{ secrets.service-account }}
          GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          python test_integrations.py
